// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-b0JWH-CM3Dys7jU3aCPLgdWPQLWSwI',
    appId: '1:294093298575:web:85e4d6315bff01385309fa',
    messagingSenderId: '294093298575',
    projectId: 'activity-shop',
    authDomain: 'activity-shop.firebaseapp.com',
    storageBucket: 'activity-shop.appspot.com',
    measurementId: 'G-8K231YFLPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9za-_VfzWVHFY8COdstsR81oVz6Jzuo',
    appId: '1:294093298575:android:1957750eef6680265309fa',
    messagingSenderId: '294093298575',
    projectId: 'activity-shop',
    storageBucket: 'activity-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGRxjIRldeZMAeG0KmKYUr3y9HNLm0pc',
    appId: '1:294093298575:ios:272b7af8eda756115309fa',
    messagingSenderId: '294093298575',
    projectId: 'activity-shop',
    storageBucket: 'activity-shop.appspot.com',
    iosBundleId: 'com.google.firebase.presents.activityShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGRxjIRldeZMAeG0KmKYUr3y9HNLm0pc',
    appId: '1:294093298575:ios:95cee991fc0efb6f5309fa',
    messagingSenderId: '294093298575',
    projectId: 'activity-shop',
    storageBucket: 'activity-shop.appspot.com',
    iosBundleId: 'com.google.firebase.presents.activityShop.RunnerTests',
  );
}
